import { z } from "zod";

const faqItemSchema = z.object({
  question: z.string().trim().min(1, "Question is required."),
  answer: z.string().trim().min(1, "Answer is required."),
});

export const settingsSchema = z.object({
  organizationName: z.string().trim().min(1, "Organization name is required."),
  logoUrl: z.string().url("Enter a valid URL.").or(z.literal("")).optional(),
  contactEmail: z.string().email("Enter a valid email.").or(z.literal("")).optional(),
  phone: z.string().trim().optional(),
  aboutText: z.string().trim().optional(),
  aboutSectionPhotoUrl: z.string().url("Enter a valid URL.").or(z.literal("")).optional(),
  facebook: z.string().url("Enter a valid URL.").or(z.literal("")).optional(),
  linkedin: z.string().url("Enter a valid URL.").or(z.literal("")).optional(),
  github: z.string().url("Enter a valid URL.").or(z.literal("")).optional(),
  heroSlide1Image: z.string().url("Enter a valid URL.").or(z.literal("")).optional(),
  heroSlide1Title: z.string().trim().optional(),
  heroSlide1Description: z.string().trim().optional(),
  heroSlide2Image: z.string().url("Enter a valid URL.").or(z.literal("")).optional(),
  heroSlide2Title: z.string().trim().optional(),
  heroSlide2Description: z.string().trim().optional(),
  heroSlide3Image: z.string().url("Enter a valid URL.").or(z.literal("")).optional(),
  heroSlide3Title: z.string().trim().optional(),
  heroSlide3Description: z.string().trim().optional(),
  activeMembersCount: z.string().trim().regex(/^\d*$/, "Use numbers only.").optional(),
  eventsDeliveredCount: z.string().trim().regex(/^\d*$/, "Use numbers only.").optional(),
  projectsShippedCount: z.string().trim().regex(/^\d*$/, "Use numbers only.").optional(),
  mentorsAndSeniorsCount: z.string().trim().regex(/^\d*$/, "Use numbers only.").optional(),
  faqs: z.array(faqItemSchema).min(1, "Add at least one FAQ.").max(12, "Keep FAQs within 12 items."),
  testimonial1Quote: z.string().trim().optional(),
  testimonial1Author: z.string().trim().optional(),
  testimonial1Meta: z.string().trim().optional(),
  testimonial2Quote: z.string().trim().optional(),
  testimonial2Author: z.string().trim().optional(),
  testimonial2Meta: z.string().trim().optional(),
  testimonial3Quote: z.string().trim().optional(),
  testimonial3Author: z.string().trim().optional(),
  testimonial3Meta: z.string().trim().optional(),
  committeeMember1Name: z.string().trim().optional(),
  committeeMember1Role: z.string().trim().optional(),
  committeeMember1Department: z.string().trim().optional(),
  committeeMember1Bio: z.string().trim().optional(),
  committeeMember1PhotoUrl: z.string().url("Enter a valid URL.").or(z.literal("")).optional(),
  committeeMember1FacebookUrl: z.string().url("Enter a valid URL.").or(z.literal("")).optional(),
  committeeMember1LinkedinUrl: z.string().url("Enter a valid URL.").or(z.literal("")).optional(),
  committeeMember1Whatsapp: z.string().trim().optional(),
  committeeMember1Email: z.string().email("Enter a valid email.").or(z.literal("")).optional(),
  committeeMember2Name: z.string().trim().optional(),
  committeeMember2Role: z.string().trim().optional(),
  committeeMember2Department: z.string().trim().optional(),
  committeeMember2Bio: z.string().trim().optional(),
  committeeMember2PhotoUrl: z.string().url("Enter a valid URL.").or(z.literal("")).optional(),
  committeeMember2FacebookUrl: z.string().url("Enter a valid URL.").or(z.literal("")).optional(),
  committeeMember2LinkedinUrl: z.string().url("Enter a valid URL.").or(z.literal("")).optional(),
  committeeMember2Whatsapp: z.string().trim().optional(),
  committeeMember2Email: z.string().email("Enter a valid email.").or(z.literal("")).optional(),
  committeeMember3Name: z.string().trim().optional(),
  committeeMember3Role: z.string().trim().optional(),
  committeeMember3Department: z.string().trim().optional(),
  committeeMember3Bio: z.string().trim().optional(),
  committeeMember3PhotoUrl: z.string().url("Enter a valid URL.").or(z.literal("")).optional(),
  committeeMember3FacebookUrl: z.string().url("Enter a valid URL.").or(z.literal("")).optional(),
  committeeMember3LinkedinUrl: z.string().url("Enter a valid URL.").or(z.literal("")).optional(),
  committeeMember3Whatsapp: z.string().trim().optional(),
  committeeMember3Email: z.string().email("Enter a valid email.").or(z.literal("")).optional(),
  committeeMember4Name: z.string().trim().optional(),
  committeeMember4Role: z.string().trim().optional(),
  committeeMember4Department: z.string().trim().optional(),
  committeeMember4Bio: z.string().trim().optional(),
  committeeMember4PhotoUrl: z.string().url("Enter a valid URL.").or(z.literal("")).optional(),
  committeeMember4FacebookUrl: z.string().url("Enter a valid URL.").or(z.literal("")).optional(),
  committeeMember4LinkedinUrl: z.string().url("Enter a valid URL.").or(z.literal("")).optional(),
  committeeMember4Whatsapp: z.string().trim().optional(),
  committeeMember4Email: z.string().email("Enter a valid email.").or(z.literal("")).optional(),
  committeeMember5Name: z.string().trim().optional(),
  committeeMember5Role: z.string().trim().optional(),
  committeeMember5Department: z.string().trim().optional(),
  committeeMember5Bio: z.string().trim().optional(),
  committeeMember5PhotoUrl: z.string().url("Enter a valid URL.").or(z.literal("")).optional(),
  committeeMember5FacebookUrl: z.string().url("Enter a valid URL.").or(z.literal("")).optional(),
  committeeMember5LinkedinUrl: z.string().url("Enter a valid URL.").or(z.literal("")).optional(),
  committeeMember5Whatsapp: z.string().trim().optional(),
  committeeMember5Email: z.string().email("Enter a valid email.").or(z.literal("")).optional(),
  committeeMember6Name: z.string().trim().optional(),
  committeeMember6Role: z.string().trim().optional(),
  committeeMember6Department: z.string().trim().optional(),
  committeeMember6Bio: z.string().trim().optional(),
  committeeMember6PhotoUrl: z.string().url("Enter a valid URL.").or(z.literal("")).optional(),
  committeeMember6FacebookUrl: z.string().url("Enter a valid URL.").or(z.literal("")).optional(),
  committeeMember6LinkedinUrl: z.string().url("Enter a valid URL.").or(z.literal("")).optional(),
  committeeMember6Whatsapp: z.string().trim().optional(),
  committeeMember6Email: z.string().email("Enter a valid email.").or(z.literal("")).optional(),
  committeeGroupPhotoUrl: z.string().url("Enter a valid URL.").or(z.literal("")).optional(),
});

export type SettingsSchema = z.infer<typeof settingsSchema>;
