import { AiAssistantLink } from "@/lib/ai/types";

export type KnowledgeSection = {
  id: string;
  title: string;
  body: string;
  keywords: string[];
  links: AiAssistantLink[];
};

export const aiQuickPrompts = [
  "What events are coming up?",
  "How do I register for an event?",
  "What happens for paid events?",
  "Who leads the club right now?",
  "How do I apply for membership?",
  "Do I need to complete my profile first?",
  "How do login and registration work?",
  "What can I do from my account dashboard?",
  "How do testimonials work?",
  "What can event managers do?",
  "How do I contact the admin team?",
  "Tell me about the committee roles",
  "What is XYZ Tech Club about?",
];

export const knowledgeSections: KnowledgeSection[] = [
  {
    id: "events",
    title: "Event registration",
    body: "Public users can browse events from the events page and open a dedicated details page for each event. Free events can be registered directly, while paid events redirect the user to Stripe checkout. If a profile is incomplete, the user must finish their account profile before registering. When an event reaches capacity, the registration flow can place the user on the waitlist instead. Past events and registration-closed events cannot be joined, and privileged admin-style accounts cannot register as participants.",
    keywords: [
      "event",
      "events",
      "register",
      "registration",
      "paid",
      "free",
      "stripe",
      "waitlist",
      "capacity",
      "profile",
      "details",
      "closed",
      "upcoming",
      "past",
    ],
    links: [
      { label: "Browse events", href: "/events" },
      { label: "Open my registrations", href: "/account/registrations" },
      { label: "Complete profile", href: "/account/profile" },
    ],
  },
  {
    id: "membership",
    title: "Membership application",
    body: "Users can apply for club membership from the apply page after signing in. The membership application now reuses account profile data such as phone, academic session, department, and student ID, so the profile should be complete before applying. Existing members, admins, super admins, and event managers do not need to submit the membership application form again. If a previous application was rejected, the user can update profile details and submit again.",
    keywords: [
      "membership",
      "member",
      "apply",
      "application",
      "join",
      "club",
      "profile",
      "student id",
      "department",
      "session",
      "rejected",
      "pending",
      "approved",
    ],
    links: [
      { label: "Apply for membership", href: "/apply" },
      { label: "Update profile", href: "/account/profile" },
      { label: "Check membership status", href: "/account/membership-status" },
    ],
  },
  {
    id: "notices",
    title: "Notices and announcements",
    body: "Club notices are available from the notices page for signed-in users. The notice area supports search by title and content, and the backend decides which notices are visible based on account access. Users should sign in to review the latest official announcements relevant to their role.",
    keywords: [
      "notice",
      "notices",
      "announcement",
      "announcements",
      "search",
      "signin",
      "role",
    ],
    links: [
      { label: "Open notices", href: "/notices" },
      { label: "Login", href: "/login" },
    ],
  },
  {
    id: "account-profile",
    title: "Account profile and event-ready setup",
    body: "The account profile is the main place to keep user information complete for membership and event registration. Name, phone, academic session, department, student ID, and district are reused by the application and registration flows. If the profile is incomplete, the system prompts the user to finish missing fields before applying for membership, submitting testimonials, or registering for events. Once membership is approved or an application is under review, some membership-related fields may stay locked.",
    keywords: [
      "profile",
      "account",
      "complete profile",
      "missing fields",
      "event-ready",
      "student id",
      "district",
      "locked",
      "edit profile",
    ],
    links: [
      { label: "Open account profile", href: "/account/profile" },
      { label: "Account dashboard", href: "/account" },
      { label: "Apply for membership", href: "/apply" },
    ],
  },
  {
    id: "membership-status",
    title: "Membership status and review progress",
    body: "Users can track their membership progress from the membership status area and from profile-related account pages. A membership application can be pending, approved, or rejected. Pending applications stay under admin review, approved users can move into the member experience, and rejected users can review the admin note, update their profile, and apply again when ready.",
    keywords: [
      "membership status",
      "status",
      "pending",
      "approved",
      "rejected",
      "review",
      "admin note",
      "progress",
    ],
    links: [
      { label: "Check membership status", href: "/account/membership-status" },
      { label: "Open account profile", href: "/account/profile" },
      { label: "Apply for membership", href: "/apply" },
    ],
  },
  {
    id: "contact",
    title: "Support and contact",
    body: "Signed-in users can send structured contact requests from the contact page. Each message stays attached to the account, and admins or super admins can review the request, add an admin note, and mark it as resolved. The contact page also shows the latest resolved admin note when available.",
    keywords: [
      "contact",
      "support",
      "message",
      "admin note",
      "resolved",
      "help",
    ],
    links: [
      { label: "Contact page", href: "/contact" },
      { label: "Login", href: "/login" },
    ],
  },
  {
    id: "auth",
    title: "Login, registration, and account access",
    body: "New users can create an account from the registration page, then sign in from the login page to access account, member, or admin areas depending on role. In normal public flows, users should register first, then complete their profile before applying for membership or joining events. Some protected pages such as notices, testimonials submission, contact history, and account tools require login before they become fully available.",
    keywords: [
      "login",
      "register",
      "sign in",
      "sign up",
      "account",
      "dashboard",
      "authentication",
      "verify email",
      "access",
    ],
    links: [
      { label: "Login", href: "/login" },
      { label: "Create account", href: "/register" },
      { label: "Open account dashboard", href: "/account" },
    ],
  },
  {
    id: "committee",
    title: "Committee and leadership",
    body: "The committee page presents the current leadership and role assignments for XYZ Tech Club. You can review session-wise committee information, position details, department context, and public profile information from the committee section.",
    keywords: [
      "committee",
      "leadership",
      "president",
      "secretary",
      "convener",
      "roles",
      "team",
      "club committee",
    ],
    links: [
      { label: "Open committee page", href: "/committee" },
      { label: "About XYZ Club", href: "/about" },
    ],
  },
  {
    id: "testimonials",
    title: "Testimonials and community feedback",
    body: "The testimonials page shows approved community feedback publicly. Signed-in users with a complete profile can submit their own testimonial for admin review. Testimonials do not appear instantly, because admins approve or reject submissions first. Users can also review their own recent testimonial submissions and any admin review note from the testimonials area.",
    keywords: [
      "testimonial",
      "testimonials",
      "feedback",
      "review",
      "approved",
      "rejected",
      "pending",
      "quote",
      "community voice",
    ],
    links: [
      { label: "Open testimonials", href: "/testimonials" },
      { label: "Complete profile", href: "/account/profile" },
      { label: "Login", href: "/login" },
    ],
  },
  {
    id: "about",
    title: "About the club",
    body: "The about page explains the club story, mission, vision, collaboration model, public impact, and what members experience inside XYZ Tech Club. It also highlights the club's practical learning culture, leadership structure, and the broader community value of workshops, projects, and coordinated campus activity.",
    keywords: [
      "about",
      "club story",
      "mission",
      "vision",
      "community",
      "impact",
      "members experience",
      "culture",
      "organization",
    ],
    links: [
      { label: "About XYZ Club", href: "/about" },
      { label: "Browse events", href: "/events" },
      { label: "Apply for membership", href: "/apply" },
    ],
  },
  {
    id: "event-manager",
    title: "Event manager access",
    body: "Event managers use the admin workspace for event operations, but their main landing area is the events dashboard rather than the global admin overview. They can work with events, payments, notices, and profile pages that allow the EVENT_MANAGER role. This is different from full admins, who also manage users, applications, and site-wide settings.",
    keywords: [
      "event manager",
      "manager",
      "event_manager",
      "dashboard",
      "admin",
      "payments",
      "notices",
      "profile",
      "access",
    ],
    links: [
      { label: "Event dashboard", href: "/admin/events" },
      { label: "Payments dashboard", href: "/admin/payments" },
      { label: "Admin profile", href: "/admin/profile" },
    ],
  },
];
